# Generated by Django 4.2.2 on 2023-07-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutbolMundial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
