# Generated by Django 4.2.2 on 2023-07-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutbolMundial', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
